site_name: HYPERION
site_description: Probabilistic Programming Language на JAX
repo_url: https://github.com/BusyaPrime/Hyperion
repo_name: BusyaPrime/Hyperion

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: amber
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - Главная: index.md
  - Quickstart: quickstart.md
  - API Reference:
    - DSL: api/dsl.md
    - Distributions: api/distributions.md
    - Inference: api/inference.md
    - Diagnostics: api/diagnostics.md
  - Architecture: architecture.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true
